export const movies=[
    {
        id:1,
        title:"Spider Man: No Way Home",
        poster:"https://tse4.mm.bing.net/th?id=OIP.mPlcfmeTiAVS5BJcN_P_lQHaEK&pid=Api&P=0&h=180",
        plot:"With Spider-Man's identity now revealed , Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        price:199,
        rating:8.2,
        stars:0,
        fav:false,
        cart:false,
    },
    {
        id:2,
        title:"The Avengers",
        poster:"https://tse3.mm.bing.net/th?id=OIP.97ULK61pHA4Q8eCLD2XGPQHaEK&pid=Api&P=0&h=180",
        plot:"Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
        price:295,
        rating:8.0,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:3,
        title:"Oppenheimer",
        poster:"https://tse2.mm.bing.net/th?id=OIP.YxctLb0kb_8Z0k3q6cQW-AHaD4&pid=Api&P=0&h=180",
        plot:"The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.",
        price:399,
        rating:8.6,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:4,
        title:"The Lord of the Rings: The Fellowship of the Ring",
        poster:"https://tse3.mm.bing.net/th?id=OIP.KzWXEC3LniUXvcwMvnSi0AHaEK&pid=Api&P=0&h=180",
        plot:"A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        price:299,
        rating:8.8,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:5,
        title:"Inception",
        poster:"https://tse1.mm.bing.net/th?id=OIP.EI-h6SO0PdExgxUN51ozmQHaEK&pid=Api&P=0&h=180",
        plot:"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        price:259,
        rating:8.8,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:6,
        title:"The Lion King",
        poster:"https://tse4.mm.bing.net/th?id=OIP.s_o1EE3ni0xDvdyd82RWIQHaE7&pid=Api&P=0&h=180",
        plot:"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        price:99,
        rating:8.5,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:7,
        title:"Heart Of Stone",
        poster:"https://tse1.mm.bing.net/th?id=OIP.WeBEk5hHAKe5cKDoEElUiQHaEK&pid=Api&P=0&h=1800",
        plot:"An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable and dangerous weapon.",
        price:99,
        rating:5.7,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:8,
        title:"The Little Mermaid",
        poster:"https://tse4.explicit.bing.net/th?id=OIP.n0_MZzSqLhlyzzEjKa9ekwHaEK&pid=Api&P=0&h=180",
        plot:"A young mermaid makes a deal with a sea witch to trade her beautiful voice for human legs so she can discover the world above water and impress a prince.",
        price:189,
        rating:7.2,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:9,
        title:"Avatar: The Way of Water",
        poster:"https://tse1.mm.bing.net/th?id=OIP.lI8-PJTOegizNUh-M2ONZwHaEo&pid=Api&P=0&h=180",
        plot:"Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
        price:299,
        rating:7.6,
        stars:0,
        fav:false,
        cart:false,
    },
    {   
        id:10,
        title:"Harry Potter and the Sorcerer's Stone",
        poster:"https://tse3.mm.bing.net/th?id=OIP.iK328Z0qQITYYPFxKwfU7QHaEo&pid=Api&P=0&h=180",
        plot:"An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
        price:299,
        rating:7.6,
        stars:0,
        fav:false,
        cart:false,
    }
]